DROP TABLE SYSTEM.PARAMS;

CREATE TABLE "SYSTEM"."PARAMS" 
   (	 
	"OBJECT_ID" NUMBER(*,0) NOT NULL ENABLE,
	"ATTRIBUTE_ID" NUMBER(*,0) NOT NULL ENABLE,
	"VALUE" VARCHAR2(20 BYTE) NOT NULL ENABLE
     )

