 CREATE SEQUENCE ATTRIBUTES_SEQUENCE
 START WITH 9
 INCREMENT BY 1
 NOMAXVALUE;

CREATE TABLE "SYSTEM"."ATTRIBUTES" 
   (	"ATTRIBUTE_ID" NUMBER NOT NULL ENABLE, 
	"ATTRIBUTE_TYPE_ID" NUMBER NOT NULL ENABLE,
	"OBJECT_TYPE_ID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DETALIS" VARCHAR2(20 BYTE), 
	 PRIMARY KEY ("ATTRIBUTE_ID")
     )

