--------------------------------------------------------
--  File created - пятница-февраля-09-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ASSIGNEE
--------------------------------------------------------


 CREATE SEQUENCE ASSIGNEE_SEQUENCE
 START WITH 1
 INCREMENT BY 1
 NOMAXVALUE;
 

  CREATE TABLE "SYSTEM"."ASSIGNEE" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"LASTNAME" VARCHAR2(100 BYTE), 
	"POST" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TASK
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TASK" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"DESCRIPTIN" VARCHAR2(400 BYTE), 
	"DEADLINE" DATE, 
	"PRIORITY" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ASSIGNEE
SET DEFINE OFF;
REM INSERTING into SYSTEM.TASK
SET DEFINE OFF;
