DROP SEQUENCE OBJECT_SEQUENCE;

DROP TABLE SYSTEM.OBJECT;

 CREATE SEQUENCE OBJECT_SEQUENCE
 START WITH 9
 INCREMENT BY 1
 NOMAXVALUE;

CREATE TABLE "SYSTEM"."OBJECT" 
   (	"OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"OBJECT_TYPE_ID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	 PRIMARY KEY ("OBJECT_ID")
     )

