 CREATE SEQUENCE OBJECT_TYPES_SEQUENCE
 START WITH 3
 INCREMENT BY 1
 NOMAXVALUE;

CREATE TABLE "SYSTEM"."OBJECT_TYPES" 
   (	"OBJECT_TYPE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	 PRIMARY KEY ("OBJECT_TYPE_ID")
     )